### ISSUE TITLE
Not_exists reportando em local errado

### ISSUE THREAD

**Issue by diogosmendonca** [diogosmendonca/PatternLanguage#10]
No padrão e código abaixo o alerta é gerado duas vezes. A primeira marca a classe, o que está correto. Já a segunda marca o método, o que está conceitualmente errado, visto que o alerta deveria ser gerado na classe e não faz sentido este tipo de alerta em um método.
Padrão:
```java
//Alert: Create in facade studentSpecificService with the same name and signature from those it will expose. Make it call the business object.
public class SomeFacade{
  
    //not_exists
    public static String studentSpecificService(){
    }

}
```

Código:
```java
package  com.github.diogosmendonca.control;

import com.github.diogosmendonca.control.*;

public class ControlFacade{

    public static String diciplineSpecificService(){
        return DiciplineBusinessObject.diciplineSpecificService();
    }

}
```

Alerta Gerado:
```

2020-10-27 14:35:24,189 INFO  - File: .\src\main\java\com\github\diogosmendonca\control\ControlFacade.java
2020-10-27 14:35:24,189 INFO  - Alert Message: Create in facade studentSpecificService with the same name and signature from those it will expose. Make it call the business object.
2020-10-27 14:35:24,200 INFO  - Start: L: 5 C: 1
2020-10-27 14:35:24,204 INFO  - End: L: 5 C: 7

2020-10-27 14:35:24,204 INFO  - Alert Message: Create in facade studentSpecificService with the same name and signature from those it will expose. Make it call the business object.
2020-10-27 14:35:24,204 INFO  - Start: L: 7 C: 5
2020-10-27 14:35:24,205 INFO  - End: L: 7 C: 18
```

**Comment by deniscrispe** [comment]
> No padrão e código abaixo o alerta é gerado duas vezes. A primeira marca a classe, o que está correto. Já a segunda marca o método, o que está conceitualmente errado, visto que o alerta deveria ser gerado na classe e não faz sentido este tipo de alerta em um método.
> Padrão:
> 
> ```java
> //Alert: Create in facade studentSpecificService with the same name and signature from those it will expose. Make it call the business object.
> public class SomeFacade{
>   
>     //not_exists
>     public static String studentSpecificService(){
>     }
> 
> }
> ```
> 
> Código:
> 
> ```java
> package  com.github.diogosmendonca.control;
> 
> import com.github.diogosmendonca.control.*;
> 
> public class ControlFacade{
> 
>     public static String diciplineSpecificService(){
>         return DiciplineBusinessObject.diciplineSpecificService();
>     }
> 
> }
> ```
> 
> Alerta Gerado:
> 
> ```
> 
> 2020-10-27 14:35:24,189 INFO  - File: .\src\main\java\com\github\diogosmendonca\control\ControlFacade.java
> 2020-10-27 14:35:24,189 INFO  - Alert Message: Create in facade studentSpecificService with the same name and signature from those it will expose. Make it call the business object.
> 2020-10-27 14:35:24,200 INFO  - Start: L: 5 C: 1
> 2020-10-27 14:35:24,204 INFO  - End: L: 5 C: 7
> 
> 2020-10-27 14:35:24,204 INFO  - Alert Message: Create in facade studentSpecificService with the same name and signature from those it will expose. Make it call the business object.
> 2020-10-27 14:35:24,204 INFO  - Start: L: 7 C: 5
> 2020-10-27 14:35:24,205 INFO  - End: L: 7 C: 18
> ```

Como trabalhamos com uma busca em árvore, preciso percorrer até o final procurando o nó procurado. Porém o nó modificador deve seguir uma restrição, não pode ser buscado até o fim. Logo, o seu nó pai deve ter como nó correspondente o pai de seu correspondente, ou seja, dois modificadores são correspondente caso seus pais sejam correspondentes.

O que aconteceu nesse exemplo é que a busca foi executada duas vezes. Uma o modificador deu match com o modificador da classe e na outra vez deu match com o modificador do método (de forma errada).

Não existia essa verificação, vou adicionar.
