### ISSUE TITLE
Localização de padrões dentro do mais de dois níveis de blocos não funciona

### ISSUE THREAD

**Issue by diogosmendonca** [diogosmendonca/PatternLanguage#15]
O padrão de código abaixo não é encontrado quando está dentro de um switch.

Padrão:
```Java
public class SomeClass{
    public static void main(String[] args){
        //Alert: ControlFacade cannot be called from view package, call a command instead.
        ControlFacade.someMethod();
    }
}
```

Código:
```Java
package com.github.diogosmendonca.view;

import com.github.diogosmendonca.control.*;

public class Main{

    private static String output = null;

    public static void main(String[] args){
        String result = null;
        if(args != null && args.length > 0){
            switch(args[0]){
                case "studentSpecificCommand":
                    result = ControlFacade.studentSpecificService();
                    break;
                case "diciplineSpecificCommand":
                    result = ControlFacade.diciplineSpecificService();
                    break;
                default:
                    result = "Command not found";
                    break;
            }
        }else{
            result = "Command not found";
        }
        System.out.println(result);
        output = result;
    }

    public static String getOutput(){
        return output;
    }

}
```

**Comment by diogosmendonca** [comment]
Abri esta issue achando que o problema era com o Switch, mas aparentemente é com o nível de profundidade dos blocos. No exemplo abaixo também não funciona.
```Java
package com.github.diogosmendonca.view;

import com.github.diogosmendonca.control.*;

public class Main{

    private static String output = null;

    public static void main(String[] args){
        String result = null;
        if(args != null && args.length > 0){
            if(args[0].equals("studentSpecificCommand")){
                result = ControlFacade.studentSpecificService();
            }else if (args[0].equals("diciplineSpecificCommand")){
                result = ControlFacade.diciplineSpecificService();
            }else{
                result = "Command not found";
            }
        }else{
            result = "Command not found";
        }
        System.out.println(result);
        output = result;
    }

    public static String getOutput(){
        return output;
    }

}
```

**Comment by deniscrispe** [comment]
O padrão é encontrado sim, o problema foi na solução da issue 6, onde eu deixei de passar o alerta dos pais para os filhos.

Segue a abaixo as AST para melhor compreensão

Árvore do padrão:

**ControlFacade.someMethod(); (ExpressionStatementTree)**
    ControlFacade.someMethod() (MethodInvocationTree) 
        ControlFacade.someMethod (MemberSelectTree) 
            ControlFacade (IdentifierTree)

Árvore do código-fonte:

**result = ControlFacade.studentSpecificService(); (ExpressionStatementTree)** 
    result = ControlFacade.studentSpecificService() (AssignmentTree)
        result (IdentifierTree)
        ControlFacade.studentSpecificService() (MethodInvocationTree)
            ControlFacade.studentSpecificService (MemberSelectTree)
                ControlFacade (IdentifierTree)

No caso desse padrão, quando tenho uma ExpressionStatementTree eu tenho que "ignorar" e começar a buscar a partir do seu filho, no caso desse padrão a MethodInvocationTree. Não posso comparar as duas ExpressionStatementTree pois "ControlFacade.someMethod();" != "result = ControlFacade.studentSpecificService();".

Resumindo, eu procuro neste caso um ControlFacade.someMethod() (MethodInvocationTree)  que é encontrado sim , porém como o alerta está em seu pai ExpressionStatementTree o retorno é vazio.

Irei corrigir e já subo.
